import{useEffect,useState}from'react';
import{CheckCircle2,Download,FileText,Send,Upload,X}from'lucide-react';
import{erpApi}from'../../services/api';
import{SCHOOL_CLASSES}from'../../config/schoolOptions';

const toBase64=file=>new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=bad;r.readAsDataURL(file)});

export default function HomeworkWorkspace({type,role}){
  const[rows,setRows]=useState([]),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const teacher=role==='TEACHER';
  const load=async()=>{setLoading(true);setError('');try{const data=await erpApi.records(type);setRows(data.records||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[type]);
  async function publish(e){e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget),pdf=f.get('file');if(pdf?.size>3*1024*1024)throw new Error('PDF must be 3 MB or smaller');if(pdf?.size&&!pdf.name.toLowerCase().endsWith('.pdf'))throw new Error('Only PDF files can be uploaded');const file=pdf?.size?{name:pdf.name,data:await toBase64(pdf)}:null;await erpApi.publishHomework({module:type,title:f.get('title'),className:f.get('class'),subject:f.get('subject'),instructions:f.get('instructions'),due:f.get('due'),file});setOpen(false);setMessage(`${type} published successfully.`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <section className="modulepage"><div className="modulebar"><div><span className="kicker">{teacher?'TEACHER PUBLISHING':'STUDENT LEARNING'}</span><h2>{type}</h2><p>{teacher?'Publish instructions and PDF resources to your classes.':'View your assigned work and download teacher resources.'}</p></div>{teacher&&<button className="btn" onClick={()=>{setError('');setMessage('');setOpen(true)}}><Upload/> Create & upload PDF</button>}</div>{message&&<p className="successbanner"><CheckCircle2/>{message}</p>}{loading?<div className="emptystate">Loading {type.toLowerCase()}…</div>:!open&&error?<div className="emptystate error"><p>{error}</p><button className="btn" onClick={load}>Retry module</button></div>:rows.length===0?<div className="emptystate">No {type.toLowerCase()} available yet.</div>:<div className="recordgrid">{rows.map(r=><article className="record homeworkrecord" key={r.id}><div className="recordicon"><FileText/></div><div><h3>{r.title}</h3><p>{r.subtitle}</p><span>{r.status}</span>{r.due_date&&<small>Due {r.due_date}</small>}</div>{r.attachment_id&&<button className="pdfdownload" onClick={()=>erpApi.download(r.attachment_id,r.file_name)}><Download/> Download PDF<small>{Math.ceil(r.size_bytes/1024)} KB</small></button>}</article>)}</div>}{open&&<div className="modalback"><form className="recordform teacherform" onSubmit={publish}><button type="button" className="close" onClick={()=>setOpen(false)}><X/></button><span className="kicker">PUBLISH TO CLASS</span><h2>New {type==='Homework'?'Homework':'Assignment'}</h2><div className="formrow"><label>Class<select name="class">{SCHOOL_CLASSES.map(className=><option key={className} value={className}>{className}</option>)}</select></label><label>Subject<select name="subject"><option>Mathematics</option><option>Science</option><option>English</option></select></label></div><label>Title<input name="title" required/></label><label>Instructions<textarea name="instructions"/></label><label>Deadline<input name="due" required type="date"/></label><label className="filedrop"><Upload/><span>Attach PDF (maximum 3 MB)</span><input name="file" type="file" accept="application/pdf,.pdf"/></label>{error&&<p className="formerror">{error}</p>}<button disabled={busy} className="btn"><Send/> {busy?'Uploading…':'Publish to students'}</button></form></div>}</section>
}
